name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["14.x", "16.x"]
        gatsby-version: ["3", "4"]
        # exclude:
        # - node-version: "12.x"
        #   gatsby-version: "^4.0.0"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (Gatsby ${{ matrix.gatsby-version }})
      run: |
        node .github/patchVersions.js
        yarn install --no-lockfile
      env:
        GATSBY_VERSION: ${{ matrix.gatsby-version }}
        NODE_VERSION: ${{ matrix.node-version }}
    - name: Run tests
      run: |
        cat node_modules/gatsby/package.json | grep "\"version\""
        yarn test
      env:
        CI: true
